// <auto-generated />
namespace DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingmenuoptionsusertypevalidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingmenuoptionsusertypevalidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201706191243237_adding menu options usertype validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
